### ISSUE TITLE
Some questions about main probing callback

### ISSUE THREAD

**Issue by BugenZhao** [lambdahuang/FlashRoute#4]
Hi, I'm recently working on a course project to reproduce your work, and I'd like to say that your work is so great and creative!
However I'm a little bit confused with the callback function of main probing, that is
```cpp
if (!fromDestination) {
   ...
} else {
  targetList_[blockIndex].stopForwardProbing();
}
```

My question is: shouldn't we add the target into some set (stop or discovery set) if the response is from destination? Will this cause some targets be missed?
To check this, I generate a random target list of /24 and then run the test, figuring out that adding a line like `backwardProbingStopSet_.insert(responder);` will increase the total probed interfaces from 800,000 to 1,200,000. This make me confused but it seems that no interfaces are counted more than twice indeed.

Looking forward to your reply!

**Comment by lambdahuang** [comment]
Hi Bugen,

Thanks for reaching out! FlashRoute treats destinations different from interfaces (routers). For now, FlashRoute focuses more on the route itself (consisted of a series of hops of router interfaces) so it does not take the destinations as the discovered interfaces. One can add the destinations to the discovery set offline in the result analysis but, considering some destinations are responsive and others are not, the total number will subject not only to the route discovery but also to whether or not the destinations are alive. Since those silent destinations may also be live machines but silenced by the firewall policy or other configurations, we let users decide what to do. For this reason, FlashRoute dumps all responses including those from destinations and those from the routers to the output. 

Best,
Neo Huang

**Comment by BugenZhao** [comment]
Thanks so much for your speedy reply!
I've got your idea about only counting internet routers in the result and let users decide whether to include the destinations in further analysis. And I try it out in my FlashRoute implementation and get a result of 800,000 as well, which seems fine. 
If I understand you correctly, is this a common practice for all kinds of massive-scale traceroute tools? 
Thank you again for helping me to delve deeper into this field.

**Comment by lambdahuang** [comment]
You're welcome! Your question is actually a very good one. Here is my thought. The interfaces in a traceroute scan can only be revealed by an ICMP TTL-expired message sending from routers, no matter what probes you are using. On the other hand, the destinations can be revealed by various types of methods, an ICMP pong responses to ICMP ping probe, ICMP unreachable message to UDP probes, SYN-ACK or RST to TCP probes. Although destinations may be considered as part of topology in intuition, they play a quite different role in the process of the scan. There is a different research direction to think about how to better find a list of responsive destinations, which is called Hitlist. Based on our experiment data, one trying to use destinations from Hitlist will eventually discover shorter routes and fewer router interfaces in reality. To recap my points, there are so many differences between destinations and interfaces. I believe treating destinations and interfaces separately gives us a clear scope of what to improve.

Neo Huang

**Comment by BugenZhao** [comment]
Got it! Thanks for your detailed explanations!
